packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.89.0
  "@types/node": ^24.5.0
  drizzle-orm: ^0.44.5
  nanoid: ^5.1.5
  oxlint: 1.16.0
  typescript: 5.9.2
  zod: ^4.1.5

catalogs:
  api:
    "@hono/zod-openapi": ^1.1.0
    better-auth: ^1.3.11
    hono: ^4.9.7
  mobile:
    react-native-svg: 15.12.1
  react19:
    "@types/react": ^19.1.13
    "@types/react-dom": ~19.1.9
    react: "^19.1.1"
    react-dom: "^19.1.1"
    react-native: "^0.81.4"
  ui:
    class-variance-authority: ^0.7.1
    lucide-react: ^0.544.0
    lucide-react-native: ^0.544.0
    nativewind: ^4.2.1
    sonner: ^2.0.6
    tailwind-merge: ^3.3.1
    tailwindcss: ^3.4.17

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - lefthook
  - oxc-resolver
  - sharp
  - simple-git-hooks
  - workerd

overrides:
  "@react-scan/vite-plugin-react-scan>react-scan": ^0.4.3
  "@react-scan/vite-plugin-react-scan>vite": ^7.0.6
