packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@tanstack/react-query': ^5.87.1
  '@types/node': ^24.1.0
  drizzle-orm: ^0.44.5
  nanoid: ^5.1.5
  oxlint: 1.14.0
  typescript: 5.9.2
  zod: ^4.1.5

catalogs:
  api:
    '@hono/zod-openapi': ^1.1.0
    better-auth: ^1.3.8
    hono: ^4.9.6
  mobile:
    react-native-svg: 15.11.2
  react19:
    '@types/react': ~19.0.10
    '@types/react-dom': ~19.1.9
    react: 19.0.0
    react-dom: 19.0.0
    react-native: 0.79.5
  ui:
    class-variance-authority: ^0.7.1
    lucide-react: ^0.542.0
    lucide-react-native: ^0.542.0
    nativewind: ^4.1.23
    sonner: ^2.0.6
    tailwind-merge: ^3.3.1
    tailwindcss: ^3.4.17

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - lefthook
  - oxc-resolver
  - sharp
  - simple-git-hooks
  - workerd

overrides:
  '@react-scan/vite-plugin-react-scan>react-scan': ^0.4.3
  '@react-scan/vite-plugin-react-scan>vite': ^7.0.6
