packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@biomejs/biome': 2.1.1
  oxlint: 1.6.0
  typescript: 5.8.3
  zod: ^3.25.76

catalogs:
  api:
    better-auth: ^1.2.12
    hono: ^4.8.5
  mobile:
    react-native-svg: 15.11.2
  react19:
    '@types/react': ~19.0.10
    '@types/react-dom': ~19.1.6
    react: 19.0.0
    react-dom: 19.0.0
    react-native: 0.79.5
  ui:
    class-variance-authority: ^0.7.1
    nativewind: ^4.1.23
    tailwind-merge: ^3.3.1
    tailwindcss: ^3.4.17
    lucide-react: ^0.525.0
    lucide-react-native: ^0.525.0

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - workerd
