packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@biomejs/biome': 2.0.6
  oxlint: 1.6.0
  tailwindcss: 3.4.17
  typescript: 5.8.3

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
