packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@biomejs/biome": 2.1.2
  "@types/node": ^24.1.0
  drizzle-orm: ^0.44.4
  oxlint: 1.9.0
  typescript: 5.8.3
  zod: ^4.0.14

catalogs:
  api:
    "@hono/zod-openapi": ^1.0.2
    better-auth: ^1.3.4
    hono: ^4.8.9
  mobile:
    react-native-svg: 15.11.2
  react19:
    "@types/react": ~19.0.10
    "@types/react-dom": ~19.1.6
    react: 19.0.0
    react-dom: 19.0.0
    react-native: 0.79.5
  ui:
    class-variance-authority: ^0.7.1
    lucide-react: ^0.533.0
    lucide-react-native: ^0.533.0
    nativewind: ^4.1.23
    tailwind-merge: ^3.3.1
    tailwindcss: ^3.4.17

nodeLinker: hoisted

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - lefthook
  - oxc-resolver
  - sharp
  - simple-git-hooks
  - workerd

overrides:
  "drizzle-zod>zod": ^4.0.14
