packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@biomejs/biome': 2.0.6
  oxlint: 1.6.0
  class-variance-authority: ^0.7.1
  nativewind: ^4.1.23
  tailwind-merge: ^3.3.1
  tailwindcss: 3.4.17
  typescript: 5.8.3
  zod: ^3.25.76

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    react-native: 0.79.5
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.5

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - sharp
  - simple-git-hooks
  - workerd
