packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@types/node': ^24.10.0
  '@typescript/native-preview': 7.0.0-dev.20251104.1
  better-auth: ^1.3.34
  nanoid: ^5.1.6
  oxlint: 1.25.0
  oxlint-tsgolint: ^0.5.0
  zod: ^4.1.12

catalogs:
  backend:
    '@hono/zod-openapi': ^1.1.4
    drizzle-orm: ^0.44.7
    hono: ^4.10.4
  frontend:
    '@tanstack/react-query': ^5.90.6
    class-variance-authority: 0.7.1
    lucide-react: ^0.552.0
    sonner: ^2.0.7
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.16
    tw-animate-css: ^1.4.0
  mobile:
    lucide-react-native: ^0.552.0
    nativewind: 5.0.0-preview.2
    react-native-css: ^3.0.1
    react-native-svg: 15.14.0
  react19:
    '@types/react': 19.1.17
    '@types/react-dom': 19.1.7
    react: 19.1.0
    react-dom: 19.1.0
    react-native: ^0.81.5

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - lefthook
  - oxc-resolver
  - sharp
  - simple-git-hooks
  - workerd

overrides:
  '@cloudflare/vitest-pool-workers>vitest': ^4.0.1
  vite: npm:rolldown-vite@latest
